(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-popup/uni-popup"],{"0ff1":function(t,n,i){"use strict";i.d(n,"b",(function(){return o})),i.d(n,"c",(function(){return s})),i.d(n,"a",(function(){return e}));var e={uniTransition:function(){return i.e("components/uni-transition/uni-transition").then(i.bind(null,"b0e6"))}},o=function(){var t=this,n=t.$createElement;t._self._c},s=[]},8469:function(t,n,i){"use strict";var e=i("ffee"),o=i.n(e);o.a},8930:function(t,n,i){"use strict";i.r(n);var e=i("0ff1"),o=i("a5e1");for(var s in o)"default"!==s&&function(t){i.d(n,t,(function(){return o[t]}))}(s);i("8469");var a,r=i("f0c5"),u=Object(r["a"])(o["default"],e["b"],e["c"],!1,null,"aeeae3cc",null,!1,e["a"],a);n["default"]=u.exports},a5e1:function(t,n,i){"use strict";i.r(n);var e=i("c039"),o=i.n(e);for(var s in e)"default"!==s&&function(t){i.d(n,t,(function(){return e[t]}))}(s);n["default"]=o.a},c039:function(t,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e=function(){i.e("components/uni-transition/uni-transition").then(function(){return resolve(i("b0e6"))}.bind(null,i)).catch(i.oe)},o={name:"UniPopup",components:{uniTransition:e},props:{animation:{type:Boolean,default:!0},type:{type:String,default:"center"},top:{type:Number,default:0},left:{type:Number,default:0},maskClick:{type:Boolean,default:!0}},data:function(){return{duration:300,ani:[],showPopup:!1,showTrans:!1,maskClass:{position:"fixed",bottom:0,top:0,left:0,right:0,backgroundColor:"rgba(0, 0, 0, 0.5)"},transClass:{position:"fixed",left:0,right:0,top:0}}},watch:{top:{handler:function(t){this.transClass={position:"fixed",left:this.left+"px",top:t+"px"}}},type:{handler:function(t){switch(this.type){case"top":this.ani=["slide-top"],this.transClass={position:"fixed",left:0,right:0};break;case"bottom":this.ani=["slide-bottom"],this.transClass={position:"fixed",left:0,right:0,bottom:0};break;case"center":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",display:"flex",flexDirection:"column",bottom:0,left:0,right:0,top:0,justifyContent:"center",alignItems:"center"};break;case"position":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",left:this.left,top:this.top};break}},immediate:!0}},created:function(){this.animation?this.duration=300:this.duration=0},methods:{clear:function(t){t.stopPropagation()},open:function(){var t=this;this.showPopup=!0,this.$nextTick((function(){clearTimeout(t.timer),t.timer=setTimeout((function(){t.showTrans=!0}),50)})),this.$emit("change",{show:!0}),this.$emit("noshow",this.showPopup)},close:function(t){var n=this;this.showTrans=!1,this.$nextTick((function(){clearTimeout(n.timer),n.timer=setTimeout((function(){n.$emit("change",{show:!1}),n.showPopup=!1,n.$emit("noshow",n.showPopup)}),300)}))},onTap:function(){this.maskClick&&this.close()}}};n.default=o},ffee:function(t,n,i){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-popup/uni-popup-create-component',
    {
        'components/uni-popup/uni-popup-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("8930"))
        })
    },
    [['components/uni-popup/uni-popup-create-component']]
]);
